In [3]:
from data_loader import *
import time

/home/qara/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [2]:
labeling_data(0.1)

labeling seq data

/home/qara/hogun/redditanalysis/classification2/data_loader.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['label'][top_score] = 1

In [4]:
x = load_obj('seq_data')

In [5]:
xg = x['sequence'][:100]

In [10]:
np.array(list(xg)).shape

(100, 30)

In [1]:
def padding(sequence):
    pad_len = TITLE_LEN - len(sequence)                                                          
    return np.pad(sequence, (pad_len, 0), 'constant')

In [19]:
global TITLE_LEN
TITLE_LEN = 60
seq['sequence'].apply(padding)

0          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
7          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
9          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
10         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
11         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
12         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
13         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
14         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
15         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
16         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
17         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
18         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
19         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
20         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
21         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
22         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
23         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
24         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
25         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
26         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
27         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
28         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
29         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                                 ...
1351505    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351506    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351507    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351508    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351509    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351510    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351511    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351512    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351513    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351514    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351515    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351516    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351517    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351518    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351519    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351520    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351521    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351522    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351523    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351524    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351525    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351526    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351527    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351528    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351529    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351530    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351531    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351532    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351533    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1351534    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: sequence, Length: 1351535, dtype: object

In [2]:
seq = load_obj('seq_data')

In [23]:
len(seq[seq['sequence'].apply(len)>30])

5127

In [12]:
np.pad(x, (4,0), 'constant')

array([   0,    0,    0,    0,   15,   77,  284,  508,  462,  240,  328,
         10, 2233, 9004])

In [4]:
embedding_mat = load_obj('embedding_mat')

In [5]:
len(embedding_mat)

100000

In [2]:
tokenizer = load_obj('tokenizer')

embedding_mat = make_embedding(tokenizer, 100000)

In [3]:
total_data = load_obj('total_data')

In [4]:
len(total_data)

1351535

In [5]:
total_data['sequence'] = pd.Series(tokenizer.texts_to_sequences(list(total_data['title'])), index = total_data.index)

In [6]:
total_data

,title,score,log_score,date,sequence
0,healthy skin new year,1,0.301030,2017-11-01,"[1578, 948, 2, 21]"
1,president obama wants give young leaders aroun...,5,0.778151,2017-11-01,"[15, 77, 284, 508, 462, 240, 328, 10, 2233, 9004]"
2,new york terror attack truck crash lower manha...,1,0.301030,2017-11-01,"[2, 393, 95, 13, 1213, 215, 1993, 4414, 788, 3..."
3,eu japan ask un condemn n korea rights abuses,7,0.903090,2017-11-01,"[53, 100, 1690, 42, 2885, 162, 14, 122, 3204]"
4,sell miami house fast real estate solutions,1,0.301030,2017-11-01,"[1094, 3077, 85, 843, 269, 1120, 1677]"
5,roma feast chelseas frailties give antonio con...,0,0.000000,2017-11-01,"[5981, 11787, 22418, 69895, 508, 5124, 15703, ..."
6,halloween quiz test knowledge scary pop culture,0,0.000000,2017-11-01,"[3929, 7965, 259, 2684, 6454, 3062, 2000]"
7,new york attack suspect named eight killed act...,1,0.301030,2017-11-01,"[2, 393, 13, 384, 1200, 976, 17, 782, 95]"
8,brazil oks amended bill car hailing apps uber ...,1,0.301030,2017-11-01,"[442, 8824, 18788, 245, 128, 11939, 2060, 1280..."
9,franklin p adams quotes christmas,1,0.301030,2017-11-01,"[9654, 1450, 6196, 52, 725]"
10,couple reworks baby cold outside underline imp...,1,0.301030,2017-11-01,"[1078, 69896, 331, 1222, 629, 30967, 1159, 3590]"
11,ukraine blames russia fatal ambush husband wif...,22,1.361728,2017-11-01,"[36, 1508, 7, 2176, 4985, 1331, 520, 477]"
12,nyc terror attack suspect sayfullo saipov regi...,1,0.301030,2017-11-01,"[2639, 95, 13, 384, 39717, 37770, 4997, 146, 3..."
13,kim jong nams murder china breaks north korean...,243,2.387390,2017-11-01,"[264, 475, 14110, 323, 6, 1289, 11, 167, 1010,..."
14,care skin healthy skin care nourish protect sk...,1,0.301030,2017-11-01,"[418, 948, 1578, 948, 418, 44912, 834, 948, 21..."
15,exclusive u pursues direct diplomacy north kor...,1,0.301030,2017-11-01,"[1100, 4, 14315, 1792, 3229, 11, 14, 374, 5, 7..."
16,finland takes phone call find much neighbour e...,13,1.146128,2017-11-01,"[2392, 478, 472, 238, 251, 577, 10007, 9208, 1..."
17,u pursues direct diplomacy north korea despite...,2,0.477121,2017-11-01,"[4, 14315, 1792, 3229, 11, 14, 374, 5, 7651]"
18,u pursues direct diplomacy north korea despite...,29,1.477121,2017-11-01,"[4, 14315, 1792, 3229, 11, 14, 374, 5, 7651]"
19,new york attack suspect named eight killed act...,2,0.477121,2017-11-01,"[2, 393, 13, 384, 1200, 976, 17, 782, 95]"
20,easy guidelines baseball easy adhere,1,0.301030,2017-11-01,"[817, 2274, 2747, 817, 14765]"
21,deadly attacks global attention fades quickly ...,66,1.826075,2017-11-01,"[411, 65, 108, 2867, 14111, 3072, 1097, 22822,..."
22,officer bank manafort hid money trumps sec com...,1,0.301030,2017-11-01,"[563, 147, 4901, 6703, 189, 168, 7486, 3803]"
23,terrorist new york truck attack killed isis,1,0.301030,2017-11-01,"[261, 2, 393, 1213, 13, 17, 16]"
24,james cash penney quotes communication,1,0.301030,2017-11-01,"[1158, 699, 36028, 52, 3773]"
25,system alifelong asia scam legit review proof ...,1,0.301030,2017-11-01,"[228, 90726, 709, 3167, 14112, 293, 1946, 3008]"
26,uluru climbing ban consideration traditional o...,16,1.230449,2017-11-01,"[29165, 9005, 125, 11466, 3170, 2642, 872, 88,..."
27,mexicans embrace day dead spectacle place hall...,21,1.342423,2017-11-01,"[7022, 6022, 56, 31, 15112, 682, 3929]"
28,iraq bans israeli flags kurds wave independenc...,10,1.041393,2017-11-01,"[89, 594, 43, 3820, 1091, 1463, 710, 3286]"
29,patty murray quotes health,1,0.301030,2017-11-01,"[26940, 6737, 52, 190]"
...,...,...,...,...,...
1351505,osce says another team monitors detained east ...,6,0.845098,2014-06-01,"[4979, 3, 303, 463, 5967, 759, 213, 36]"
1351506,thailand coup leader says reconciliation refor...,4,0.698970,2014-06-01,"[1019, 688, 69, 3, 6241, 1665, 144, 21, 579, 309]"
1351507,david truscott threatened kill family refused ...,1,0.301030,2014-06-01,"[610, 1482, 188, 202, 2208, 1123, 3535, 2166, ..."
1351508,petition justice gabanna dog shot pennsylvania...,3,0.602060,2014-06-01,"[1825, 720, 856, 182, 6154, 9, 733]"
1351509,pakistan launches afghan airstrikes attacks ta...,3,0.602060,2014-06-01,"[76, 447, 387, 819, 65, 491, 25024, 29874, 131..."
1351510,nasas proposed space boat runs issues,3,0.602060,2014-06-01,"[4286, 1992, 362, 1212, 2337, 681]"
1351511,transfer guantanamo detainees brings great hap...,0,0.000000,2014-06-01,"[2558, 2963, 4107, 2198, 272, 4117, 491]"
1351512,ethiopias blue volcano burns deadly sulphuric ...,0,0.000000,2014-06-01,"[10197, 1661, 2259, 3269, 411, 35395, 275, 16404]"
1351513,one founders file sharing website pirate bay p...,5,0.778151,2014-06-01,"[34, 8310, 2802, 2241, 432, 2749, 1765, 2901, ..."
1351514,petition justice petunia severely burnt dog ba...,0,0.000000,2014-06-01,"[1825, 720, 50553, 6437, 5265, 856, 5866, 733]"
1351515,bowe bergdahl possible turn usa nicolas brody,1,0.301030,2014-06-01,"[10076, 7940, 471, 795, 620, 4403, 41136]"
1351516,face arab outrage jerusalem synagogue destroye...,1,0.301030,2014-06-01,"[211, 518, 1930, 438, 4341, 1476, 1456, 18483,..."
1351517,chan banned russia,1,0.301030,2014-06-01,"[5292, 645, 7]"
1351518,qatar world cup payments officials corruption ...,5,0.778151,2014-06-01,"[602, 10, 607, 2919, 117, 479, 565]"
1351519,st source bank tried destroy fighting back,1,0.301030,2014-06-01,"[538, 907, 147, 1233, 1446, 409, 84]"
1351520,malaysian girl gang raped men several hours,3,0.602060,2014-06-01,"[981, 243, 801, 769, 179, 668, 502]"
1351521,canada pledges billion improving maternal heal...,71,1.857332,2014-06-01,"[176, 1965, 169, 5246, 13422, 190, 684, 10, 221]"
1351522,ukraine russia gas talks go wire,11,1.079181,2014-06-01,"[36, 7, 275, 131, 218, 4978]"
1351523,south korean missionary sentenced life hard la...,2,0.477121,2014-06-01,"[28, 167, 9928, 662, 102, 1130, 1088, 11, 14]"
1351524,great job brazil put money using needles hospi...,0,0.000000,2014-06-01,"[272, 779, 442, 650, 189, 266, 16861, 2508]"
1351525,regional tensions rise chinas grab gas oil,5,0.778151,2014-06-01,"[1774, 897, 457, 216, 4009, 275, 111]"
1351526,flights remain grounded ash clouds clog air ro...,1,0.301030,2014-06-01,"[1059, 1542, 8418, 5134, 7323, 28737, 72, 7289]"
1351527,picture saudi policeman leaning makkahs sacred...,1,0.301030,2014-06-01,"[1855, 45, 3587, 12581, 46340, 7939, 34365]"
1351528,hypervocal kid uses dads passport coloring boo...,1,0.301030,2014-06-01,"[3500, 1540, 8331, 2973, 6858, 959, 350, 3568,..."
1351529,bowe bergdahl taliban captive since freed amer...,1,0.301030,2014-06-01,"[10076, 7940, 491, 4279, 229, 1522, 137, 19632..."
1351530,bowe bergdahl taliban captive since freed amer...,1,0.301030,2014-06-01,"[10076, 7940, 491, 4279, 229, 1522, 137, 19632..."
1351531,mistakes avoid networking,1,0.301030,2014-06-01,"[4077, 1108, 7266]"
1351532,patriarch bartholomew primary leader eastern o...,5,0.778151,2014-06-01,"[11042, 43488, 3319, 69, 494, 3421, 1179, 1901..."
1351533,b h obamas national security flops keep coming...,0,0.000000,2014-06-01,"[686, 1669, 1327, 175, 64, 15673, 571, 847, 37..."
1351534,cent punched jay z face bet video,1,0.301030,2014-06-01,"[2779, 6399, 5242, 4857, 211, 3981, 38]"

In [ ]:
s, e=load_data()

save data
save tokenizer
embedding: 76954
no matching: 23045
save embedding matrix